### ISSUE TITLE
ExceptionConverter: Missing "message.contains(..)" checks lead to NullPointerException

### ISSUE THREAD

**Issue by flohmueller** [gturri/dokuJClient#22] opened 2015-03-17 07:05 UTC
There's (at least) one missing block `if(message.contains(...))` for `The requested page does not exist`.

atm this results in a nasty NullPointerException a few lines further down, where `e.getCause().getClass()` is checked, because `e.getCause()` is `null`. Please add `e.getClause() != null &&`.

I'm using your latest code (from master) and DokuWiki Hrun.

List of other "missing" exception messages I found when I searched DokuWiki for RemoteExceptions:
"Empty page ID"
"You are not allowed to edit this page"
"Filename not given"
"You don't have permissions to upload files"
plus: a bunch of localized error messages from dokuwiki's media.php->media_save(..)

**Comment by gturri** [comment] 2015-03-17 08:53
Thanks for this bug report!

I'm unable to reproduce the issue for `The requested page does not exist`. Could you please tell me which command you're using to get this error?

Regarding the NullPointerException, I'm not sure I understand: it looks like we already check that `e.getCause` isn't `null`:
* https://github.com/gturri/dokuJClient/blob/master/src/main/java/dw/xmlrpc/ExceptionConverter.java#L47
* https://github.com/gturri/dokuJClient/blob/master/src/main/java/dw/xmlrpc/ExceptionConverter.java#L88

Could you explain to me what I'm missing?

Thanks!

**Comment by gturri** [comment] 2015-03-23 09:30
Thanks for pointing out those exceptions I missed. Indeed, DokuJClient didn't handled the case `"You don't have permissions to upload files"`. It's now fixed

Regarding the others, I believe they're either already handled, or impossible to get using this API (eg: a user of dokujclient has to give a pageId, so it can't fail with `"Empty page ID"`)

I'm still not able to reproduce the issue with `The requested page does not exist`: when I try

    String output = _client.getPage("doesNotExist");
    System.out.println(output);

I just get an empty output string.

Could you give me more information to help me reproduce the issue?

**Comment by flohmueller** [comment] 2015-03-25 14:28
Hi Guillaume!

Thank you for your answer.. and sorry I could not answer earlier.

Regarding the NullPointerException, to my surprise it looks like I didn't have the latest code. My git must have been lying to me.. :(

To get the `The requested page does not exist` error you have to call `getPageInfo` - `getPage` indeed returns an empty string.

As for the other messages.. I only made a list of all the DokuWiki `RemoteException`s I could find, but I didn't check if you could really encounter any of those by using your DokuJClient.

**Comment by gturri** [comment] 2015-03-25 18:45
Thanks for those precisions!
I'll dig into this soon!

**Closed** 2015-03-30 18:00 UTC
