### ISSUE TITLE
client.getAllPages() fails with XMLRPCException but CLI works

### ISSUE THREAD

**Issue by micgro42** [gturri/dokuJClient#25] opened 2015-09-17 10:33 UTC
When I try to `getAllPages` or `getRecentChanges` from my wiki I get the error `de.timroes.axmlrpc.XMLRPCException: Error getting result from server.` However `client.getTitle()`  and `client.getPageHTML("start")` work fine and so does the CLI-command:
```bash
./dokujclient --user ... --password ... --url http://127.0.0.1/~michael/dokuwiki/lib/exe/xmlrpc.php getAllPages
```

Here is my java-code:
```java
private static final int SECONDS_IN_DAY = 24 * 60 * 60;

public Map getWikiData() {
        Map contextMap = new HashMap();

        // Set access data, will later be done via config
        String url = "http://127.0.0.1/~michael/dokuwiki/lib/exe/xmlrpc.php";
        String api_user = "...";
        String api_pwd = "...";

        Date currentDate  = new Date();
        Integer recentDatePeriod = (int)(currentDate.getTime() / 1000 - 30 * SECONDS_IN_DAY);


        // initialise relevant variables
        String wikiTitle = "request failed!";
        List<PageChange> recentChanges = Collections.emptyList();
        List<Page> allPages = Collections.emptyList();

        // try to get data from the server
        try {
            DokuJClient client = new DokuJClient(url, api_user, api_pwd);
            wikiTitle = client.getTitle();

            try {
                allPages = client.getAllPages();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            try {
                recentChanges = client.getRecentChanges(recentDatePeriod);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        // store data
        contextMap.put("wikiTitle", wikiTitle);
        contextMap.put("recentChanges", recentChanges.toString());
        contextMap.put("allPages", allPages.toString());

        return contextMap;
    }
```
I'm using the current DokuWiki master-Branch (i.e. Detritus) and your maven repo for the java sources and the link from the README for the CLI-binaries.

Any ideas?

**Comment by gturri** [comment] 2015-09-17 12:28
Thank you for this bug report.

Can you please tell me the version of aXMLRPC you're using? If it's 1.8.0, then please try with 1.8.1.

**Comment by micgro42** [comment] 2015-09-17 12:49
I have been using version 3.2.0 from your maven repository per your README. But also the newest version 3.3.0 of DokuJClient at maven has still only aXMLRPC 1.8.0 listed.

I will now try to build DokuJClient from source with aXMLRPC 1.8.1. Would you consider pushing your current release to maven?

**Comment by gturri** [comment] 2015-09-17 13:12
No need to build aXMLRPC: you can download it from https://bintray.com/search?query=axmlrpc
Also, I believe you don't need to re-build dokujclient: it should work if you just replace the aXMLRPC jar.

Some more details on this issue:
* Detritus doesn't use the same format as before for dates, and aXMLRPC 1.8.0 is unable to parse those dates (this is fixed in aXMLRPC 1.8.1)
* But with aXMLRPC 1.8.1 @timroes, the author of aXMLRPC, started using JCenter instead of maven central, that's why I couldn't publish dokujclient on maven central anymore

I can think of a few solutions:

* if you're only interested in the executable, you may download it from my server: http://turri.fr/dokujclient/

* We could distribute dokujclient from jcenter (I didn't had much time to look into it)

* We could ask @timroes to publish aXMLRPC 1.8.1 on maven central as well (I've asked him a few weeks ago, but it seems he doesn't have much time to dedicate to this project anymore. Perhaps you could ping him as well, to show that there's some demand)

Anyway, please, let me know if using aXMLRPC 1.8.1 actually fixes your issue

**Comment by micgro42** [comment] 2015-09-17 15:02
Hey, either I did something wrong (which is very possible, this is my first project with java/maven) or it did not work. My current workaround is to use dokuwiki Hrun instead and maybe to write a compatibility plugin for Detritus.

I also opened an issue timroes/aXMLRPC#48 to ask @timroes to publish it on maven central.

**Comment by gturri** [comment] 2015-09-17 15:04
ok. I'll try to investigate further soon.

**Comment by gturri** [comment] 2015-09-17 20:17
I added a section about this issue in the README  (warning at the top, and workaround until the issue is fixed, at the bottom).

I would be grateful if you could tell me if it actually fixes your issue, and if, as a user who is experimenting this issue, you find it useful.

**Comment by micgro42** [comment] 2015-09-18 10:23
This is helpful, but I have some feedback:
- There is a relevant typo in the second sentence at the second section. It has to read: "The issue is that this version **has** been released on JCenter, but not on maven central."
- I use Java 8 and there a new feature "doclint" is activated by default which causes the build process to fail. The workaround from the accepted answer on [SO](http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete) worked for me as well:
```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>2.9.1</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <additionalparam>-Xdoclint:none</additionalparam>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
However that may or may not break the build process on java 7 or 6.

All in all this issue seems to work so far for me. I can now correctly parse Detritus timestamps. However I have yet to test if this setup is portable enough for my purposes. I will give feedback as soon as I know more.

**Comment by gturri** [comment] 2015-09-19 11:14
Since timroes now explains he is looking for a new maintainer for axmlrpc, I went ahead, pushed a fork on maven central, and compile against it.

Long story short: if you upgrade to dokujclient 3.6.0, everything should work fine without requiring any workaround.

Do not hesitate to open this issue again if you believe the situation isn't actually solved.

**Closed by gturri** 2015-09-19 11:14 UTC

**Comment by micgro42** [comment] 2015-09-22 14:51
It appears to work for me. A lot of thanks! :)
